config/routes.rb
Rails.application.routes.draw do
  root 'base_pages#home'

  get 'base_pages/help'

  resources :towers

  resources :powersupplies

  resources :hdds

  resources :drams

  resources :gpus

  resources :ssds

  resources :cpus

  resources :motherboards

  get 'pc_builds' => 'pc_builds#index'

end

app/models/cpu.rb
class Cpu < ActiveRecord::Base
  scope :lga1150, -> {where socket: 'lga 1150'}
  scope :lga2011, -> {where socket: 'lga 2011-v3'} 
  scope :i74790k, -> {where name: 'core i7-4790k'}
  scope :selected, -> {where select: "true"}
end

app/controllers/cpus_controller.rb
class CpusController < ApplicationController
  before_action :set_cpu, only: [:show, :edit, :update, :destroy]

  # GET /cpus
  # GET /cpus.json
  def index
    @cpus = Cpu.all

#    @chart = LazyHighCharts::HighChart.new('graph') do |f|
#      f.title(:text => "Population vs GDP For 5 Big Countries [2009]")
#      f.xAxis(:categories => ["United States", "Japan", "China", "Germany", "France"])
#      f.series(:name => "GDP in Billions", :yAxis => 0, :data => [14119, 5068, 4985, 3339, 2656])
#      f.series(:name => "Population in Millions", :yAxis => 1, :data => [310, 127, 1340, 81, 65])
#    
#      f.yAxis [
#        {:title => {:text => "GDP in Billions", :margin => 70} },
#        {:title => {:text => "Population in Millions"}, :opposite => true},
#      ]
#    
#      f.legend(:align => 'right', :verticalAlign => 'top', :y => 75, :x => -50, :layout => 'vertical',)
#      f.chart({:defaultSeriesType=>"column"})
#    end
    #render "index" , layout: "application"
  end

  # GET /cpus/1
  # GET /cpus/1.json
  def show
  end

  # GET /cpus/new
  def new
    @cpu = Cpu.new
  end

  # GET /cpus/1/edit
  def edit
  end

  # POST /cpus
  # POST /cpus.json
  def create
    @cpu = Cpu.new(cpu_params)

    respond_to do |format|
      if @cpu.save
        format.html { redirect_to @cpu, notice: 'Cpu was successfully created.' }
        format.json { render :show, status: :created, location: @cpu }
      else
        format.html { render :new }
        format.json { render json: @cpu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cpus/1
  # PATCH/PUT /cpus/1.json
  def update
    respond_to do |format|
      if @cpu.update(cpu_params)
        format.html { redirect_to @cpu, notice: 'Cpu was successfully updated.' }
        format.json { render :show, status: :ok, location: @cpu }
      else
        format.html { render :edit }
        format.json { render json: @cpu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cpus/1
  # DELETE /cpus/1.json
  def destroy
    @cpu.destroy
    respond_to do |format|
      format.html { redirect_to cpus_url, notice: 'Cpu was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cpu
      @cpu = Cpu.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cpu_params
      params.require(:cpu).permit(:select, :price, :name, :model, :socket, :cores, :threads, :operating_frequency, :max_frequency, :l2_cache, :l3_cache, :tech_node, :supports_64bits, :supports_hyper_threading, :supports_virtualization, :integrated_graphics, :graphics_base_frequency, :graphics_max_frequency, :pcie_rev, :max_pcie_lanes, :cooling_device)
    end
end

app/helpers/cpus_helper.rb
module CpusHelper
end

app/views/cpus/_form.html.erb
<%= form_for(@cpu) do |f| %>
  <% if @cpu.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cpu.errors.count, "error") %> prohibited this cpu from being saved:</h2>

      <ul>
      <% @cpu.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :select %><br>
    <%= f.text_field :select%>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :model %><br>
    <%= f.text_field :model %>
  </div>
  <div class="field">
    <%= f.label :socket %><br>
    <%= f.text_field :socket %>
  </div>
  <div class="field">
    <%= f.label :cores %><br>
    <%= f.number_field :cores %>
  </div>
  <div class="field">
    <%= f.label :threads %><br>
    <%= f.number_field :threads %>
  </div>
  <div class="field">
    <%= f.label :operating_frequency %><br>
    <%= f.text_field :operating_frequency %>
  </div>
  <div class="field">
    <%= f.label :max_frequency %><br>
    <%= f.text_field :max_frequency %>
  </div>
  <div class="field">
    <%= f.label :l2_cache %><br>
    <%= f.text_field :l2_cache %>
  </div>
  <div class="field">
    <%= f.label :l3_cache %><br>
    <%= f.text_field :l3_cache %>
  </div>
  <div class="field">
    <%= f.label :tech_node %><br>
    <%= f.text_field :tech_node %>
  </div>
  <div class="field">
    <%= f.label :supports_64bits %><br>
    <%= f.text_field :supports_64bits %>
  </div>
  <div class="field">
    <%= f.label :supports_hyper_threading %><br>
    <%= f.text_field :supports_hyper_threading %>
  </div>
  <div class="field">
    <%= f.label :supports_virtualization %><br>
    <%= f.text_field :supports_virtualization %>
  </div>
  <div class="field">
    <%= f.label :integrated_graphics %><br>
    <%= f.text_field :integrated_graphics %>
  </div>
  <div class="field">
    <%= f.label :graphics_base_frequency %><br>
    <%= f.text_field :graphics_base_frequency %>
  </div>
  <div class="field">
    <%= f.label :graphics_max_frequency %><br>
    <%= f.text_field :graphics_max_frequency %>
  </div>
  <div class="field">
    <%= f.label :pcie_rev %><br>
    <%= f.text_field :pcie_rev %>
  </div>
  <div class="field">
    <%= f.label :max_pcie_lanes %><br>
    <%= f.number_field :max_pcie_lanes %>
  </div>
  <div class="field">
    <%= f.label :cooling_device %><br>
    <%= f.text_field :cooling_device %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cpus/edit.html.erb
<h1>Editing Cpu</h1>

<%= render 'form' %>

<%= link_to 'Show', @cpu %> |
<%= link_to 'Back', cpus_path %>

app/views/cpus/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Cpus</h1>

<table class="table table-striped table-bordered table-condensed">
  <thead>
    <tr>
      <th>Select</th>
      <th>Price</th>
      <th>Name</th>
      <th>Model</th>
      <th>Socket</th>
      <th>Cores</th>
      <th>Threads</th>
      <th>Operating frequency</th>
      <th>Max frequency</th>
      <th>L2 cache</th>
      <th>L3 cache</th>
      <th>Tech node</th>
      <th>Supports 64bits</th>
      <th>Supports hyper threading</th>
      <th>Supports virtualization</th>
      <th>Integrated graphics</th>
      <th>Graphics base frequency</th>
      <th>Graphics max frequency</th>
      <th>Pcie rev</th>
      <th>Max pcie lanes</th>
      <th>Cooling device</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cpus.each do |cpu| %>
      <tr>
	<td><%= cpu.select %></td>
	<td><%= cpu.price %></td>
        <td><%= cpu.name %></td>
        <td><%= cpu.model %></td>
        <td><%= cpu.socket %></td>
        <td><%= cpu.cores %></td>
        <td><%= cpu.threads %></td>
        <td><%= cpu.operating_frequency %></td>
        <td><%= cpu.max_frequency %></td>
        <td><%= cpu.l2_cache %></td>
        <td><%= cpu.l3_cache %></td>
        <td><%= cpu.tech_node %></td>
        <td><%= cpu.supports_64bits %></td>
        <td><%= cpu.supports_hyper_threading %></td>
        <td><%= cpu.supports_virtualization %></td>
        <td><%= cpu.integrated_graphics %></td>
        <td><%= cpu.graphics_base_frequency %></td>
        <td><%= cpu.graphics_max_frequency %></td>
        <td><%= cpu.pcie_rev %></td>
        <td><%= cpu.max_pcie_lanes %></td>
        <td><%= cpu.cooling_device %></td>
        <td><%= link_to 'Show', cpu %></td>
        <td><%= link_to 'Edit', edit_cpu_path(cpu) %></td>
        <td><%= link_to 'Destroy', cpu, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<!--
$('#container').highcharts({
new Highcharts.Chart({
renderTo: "chart1"


<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js" type="text/javascript" charset="utf-8"></script>
<script src="file://localhost/Users/henryorosco/Downloads/jquery-ujs-master/src/rails.js"></script>
<script src="file://localhost/Users/henryorosco/Downloads/Highcharts-4.1.5/js/highcharts.js"></script>
<script src="file://localhost/Users/henryorosco/Downloads/Highcharts-4.1.5/js/modules/exporting.js"></script>
-->
<script type="text/javascript" charset="utf-8">
  $(function () {
    $('#container').highcharts({
        chart: {
            type: 'area'
        },
        title: {
            text: 'Historic and Estimated Worldwide Population Growth by Region'
        },
        subtitle: {
            text: 'Source: Wikipedia.org'
        },
        xAxis: {
            categories: ['1750', '1800', '1850', '1900', '1950', '1999', '2050'],
            tickmarkPlacement: 'on',
            title: {
                enabled: false
            }
        },
        yAxis: {
            title: {
                text: 'Billions'
            },
            labels: {
                formatter: function () {
                    return this.value / 1000;
                }
            }
        },
        tooltip: {
            shared: true,
            valueSuffix: ' millions'
        },
        plotOptions: {
            area: {
                stacking: 'normal',
                lineColor: '#666666',
                lineWidth: 1,
                marker: {
                    lineWidth: 1,
                    lineColor: '#666666'
                }
            }
        },
        series: [{
            name: 'Asia',
            data: [502, 635, 809, 947, 1402, 3634, 5268]
        }, {
            name: 'Africa',
            data: [106, 107, 111, 133, 221, 767, 1766]
        }, {
            name: 'Europe',
            data: [163, 203, 276, 408, 547, 729, 628]
        }, {
            name: 'America',
            data: [18, 31, 54, 156, 339, 818, 1201]
        }, {
            name: 'Oceania',
            data: [2, 2, 2, 6, 13, 30, 46]
        }]
    });
  });
<!--(JQuery);-->
</script>

<%= link_to 'New Cpu', new_cpu_path %>
<!--
<img id="myImage" src="function()" width="100" height="180">
-->

<div id="container" style="width:560px; height:300px;"></div>

app/views/cpus/new.html.erb
<h1>New Cpu</h1>

<%= render 'form' %>

<%= link_to 'Back', cpus_path %>

app/views/cpus/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Select:</strong>
  <%= @cpu.select %>
</p>
<p>
  <strong>Price:</strong>
  <%= @cpu.price %>
</p>
<p>
  <strong>Name:</strong>
  <%= @cpu.name %>
</p>

<p>
  <strong>Model:</strong>
  <%= @cpu.model %>
</p>

<p>
  <strong>Socket:</strong>
  <%= @cpu.socket %>
</p>

<p>
  <strong>Cores:</strong>
  <%= @cpu.cores %>
</p>

<p>
  <strong>Threads:</strong>
  <%= @cpu.threads %>
</p>

<p>
  <strong>Operating frequency:</strong>
  <%= @cpu.operating_frequency %>
</p>

<p>
  <strong>Max frequency:</strong>
  <%= @cpu.max_frequency %>
</p>

<p>
  <strong>L2 cache:</strong>
  <%= @cpu.l2_cache %>
</p>

<p>
  <strong>L3 cache:</strong>
  <%= @cpu.l3_cache %>
</p>

<p>
  <strong>Tech node:</strong>
  <%= @cpu.tech_node %>
</p>

<p>
  <strong>Supports 64bits:</strong>
  <%= @cpu.supports_64bits %>
</p>

<p>
  <strong>Supports hyper threading:</strong>
  <%= @cpu.supports_hyper_threading %>
</p>

<p>
  <strong>Supports virtualization:</strong>
  <%= @cpu.supports_virtualization %>
</p>

<p>
  <strong>Integrated graphics:</strong>
  <%= @cpu.integrated_graphics %>
</p>

<p>
  <strong>Graphics base frequency:</strong>
  <%= @cpu.graphics_base_frequency %>
</p>

<p>
  <strong>Graphics max frequency:</strong>
  <%= @cpu.graphics_max_frequency %>
</p>

<p>
  <strong>Pcie rev:</strong>
  <%= @cpu.pcie_rev %>
</p>

<p>
  <strong>Max pcie lanes:</strong>
  <%= @cpu.max_pcie_lanes %>
</p>

<p>
  <strong>Cooling device:</strong>
  <%= @cpu.cooling_device %>
</p>

<%= link_to 'Edit', edit_cpu_path(@cpu) %> |
<%= link_to 'See all Cpus', cpus_path %>