config/routes.rb
Rails.application.routes.draw do
  root 'base_pages#home'

  get 'base_pages/help'

  resources :towers

  resources :powersupplies

  resources :hdds

  resources :drams

  resources :gpus

  resources :ssds

  resources :cpus

  resources :motherboards

  get 'pc_builds' => 'pc_builds#index'

end

app/models/tower.rb
class Tower < ActiveRecord::Base
    scope :selected, -> {where select: "true"}
end

app/controllers/towers_controller.rb
class TowersController < ApplicationController
  before_action :set_tower, only: [:show, :edit, :update, :destroy]

  # GET /towers
  # GET /towers.json
  def index
    @towers = Tower.all
  end

  # GET /towers/1
  # GET /towers/1.json
  def show
  end

  # GET /towers/new
  def new
    @tower = Tower.new
  end

  # GET /towers/1/edit
  def edit
  end

  # POST /towers
  # POST /towers.json
  def create
    @tower = Tower.new(tower_params)

    respond_to do |format|
      if @tower.save
        format.html { redirect_to @tower, notice: 'Tower was successfully created.' }
        format.json { render :show, status: :created, location: @tower }
      else
        format.html { render :new }
        format.json { render json: @tower.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /towers/1
  # PATCH/PUT /towers/1.json
  def update
    respond_to do |format|
      if @tower.update(tower_params)
        format.html { redirect_to @tower, notice: 'Tower was successfully updated.' }
        format.json { render :show, status: :ok, location: @tower }
      else
        format.html { render :edit }
        format.json { render json: @tower.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /towers/1
  # DELETE /towers/1.json
  def destroy
    @tower.destroy
    respond_to do |format|
      format.html { redirect_to towers_url, notice: 'Tower was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tower
      @tower = Tower.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tower_params
      params.require(:tower).permit(:select, :price, :maker, :model, :mb_compatibility, :front_ports)
    end
end

app/helpers/towers_helper.rb
module TowersHelper
end

app/views/towers/_form.html.erb
<%= form_for(@tower) do |f| %>
  <% if @tower.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tower.errors.count, "error") %> prohibited this tower from being saved:</h2>

      <ul>
      <% @tower.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :select %><br>
    <%= f.text_field :select%>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :maker %><br>
    <%= f.text_field :maker %>
  </div>
  <div class="field">
    <%= f.label :model %><br>
    <%= f.text_field :model %>
  </div>
  <div class="field">
    <%= f.label :mb_compatibility %><br>
    <%= f.text_field :mb_compatibility %>
  </div>
  <div class="field">
    <%= f.label :front_ports %><br>
    <%= f.text_field :front_ports %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/towers/edit.html.erb
<h1>Editing Tower</h1>

<%= render 'form' %>

<%= link_to 'Show', @tower %> |
<%= link_to 'Back', towers_path %>

app/views/towers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Towers</h1>

<table class="table table-striped table-bordered table-condensed">
  <thead>
    <tr>
      <th>Select</th>
      <th>Price</th>
      <th>Maker</th>
      <th>Model</th>
      <th>Mb compatibility</th>
      <th>Front ports</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @towers.each do |tower| %>
      <tr>
	<td><%= tower.select %></td>
        <td><%= tower.price %></td>
        <td><%= tower.maker %></td>
        <td><%= tower.model %></td>
        <td><%= tower.mb_compatibility %></td>
        <td><%= tower.front_ports %></td>
        <td><%= link_to 'Show', tower %></td>
        <td><%= link_to 'Edit', edit_tower_path(tower) %></td>
        <td><%= link_to 'Destroy', tower, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tower', new_tower_path %>

app/views/towers/new.html.erb
<h1>New Tower</h1>

<%= render 'form' %>

<%= link_to 'Back', towers_path %>

app/views/towers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Select:</strong>
  <%= @tower.select %>
</p>

<p>
  <strong>Price:</strong>
  <%= @tower.price %>
</p>

<p>
  <strong>Maker:</strong>
  <%= @tower.maker %>
</p>

<p>
  <strong>Model:</strong>
  <%= @tower.model %>
</p>

<p>
  <strong>Mb compatibility:</strong>
  <%= @tower.mb_compatibility %>
</p>

<p>
  <strong>Front ports:</strong>
  <%= @tower.front_ports %>
</p>

<%= link_to 'Edit', edit_tower_path(@tower) %> |
<%= link_to 'See all Towers', towers_path %>