config/routes.rb
Rails.application.routes.draw do
  root 'base_pages#home'

  get 'base_pages/help'

  resources :towers

  resources :powersupplies

  resources :hdds

  resources :drams

  resources :gpus

  resources :ssds

  resources :cpus

  resources :motherboards

  get 'pc_builds' => 'pc_builds#index'

end

app/models/powersupply.rb
class Powersupply < ActiveRecord::Base
  scope :selected, -> {where select: "true"}
end

app/controllers/powersupplies_controller.rb
class PowersuppliesController < ApplicationController
  before_action :set_powersupply, only: [:show, :edit, :update, :destroy]

  # GET /powersupplies
  # GET /powersupplies.json
  def index
    @powersupplies = Powersupply.all
  end

  # GET /powersupplies/1
  # GET /powersupplies/1.json
  def show
  end

  # GET /powersupplies/new
  def new
    @powersupply = Powersupply.new
  end

  # GET /powersupplies/1/edit
  def edit
  end

  # POST /powersupplies
  # POST /powersupplies.json
  def create
    @powersupply = Powersupply.new(powersupply_params)

    respond_to do |format|
      if @powersupply.save
        format.html { redirect_to @powersupply, notice: 'Powersupply was successfully created.' }
        format.json { render :show, status: :created, location: @powersupply }
      else
        format.html { render :new }
        format.json { render json: @powersupply.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /powersupplies/1
  # PATCH/PUT /powersupplies/1.json
  def update
    respond_to do |format|
      if @powersupply.update(powersupply_params)
        format.html { redirect_to @powersupply, notice: 'Powersupply was successfully updated.' }
        format.json { render :show, status: :ok, location: @powersupply }
      else
        format.html { render :edit }
        format.json { render json: @powersupply.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /powersupplies/1
  # DELETE /powersupplies/1.json
  def destroy
    @powersupply.destroy
    respond_to do |format|
      format.html { redirect_to powersupplies_url, notice: 'Powersupply was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_powersupply
      @powersupply = Powersupply.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def powersupply_params
      params.require(:powersupply).permit(:select, :price, :maker, :model, :ps_type, :max_power, :connector, :rails_12v, :intel_support, :sli_support, :output_ratings, :dimensions, :notes)
    end
end

app/helpers/powersupplies_helper.rb
module PowersuppliesHelper
end

app/views/powersupplies/_form.html.erb
<%= form_for(@powersupply) do |f| %>
  <% if @powersupply.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@powersupply.errors.count, "error") %> prohibited this powersupply from being saved:</h2>

      <ul>
      <% @powersupply.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :select %><br>
    <%= f.text_field :select %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :maker %><br>
    <%= f.text_field :maker %>
  </div>
  <div class="field">
    <%= f.label :model %><br>
    <%= f.text_field :model %>
  </div>
  <div class="field">
    <%= f.label :ps_type %><br>
    <%= f.text_field :ps_type %>
  </div>
  <div class="field">
    <%= f.label :max_power %><br>
    <%= f.text_field :max_power %>
  </div>
  <div class="field">
    <%= f.label :connector %><br>
    <%= f.text_field :connector %>
  </div>
  <div class="field">
    <%= f.label :rails_12v %><br>
    <%= f.text_field :rails_12v %>
  </div>
  <div class="field">
    <%= f.label :intel_support %><br>
    <%= f.text_field :intel_support %>
  </div>
  <div class="field">
    <%= f.label :sli_support %><br>
    <%= f.text_field :sli_support %>
  </div>
  <div class="field">
    <%= f.label :output_ratings %><br>
    <%= f.text_field :output_ratings %>
  </div>
  <div class="field">
    <%= f.label :dimensions %><br>
    <%= f.text_field :dimensions %>
  </div>
  <div class="field">
    <%= f.label :notes %><br>
    <%= f.text_field :notes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/powersupplies/edit.html.erb
<h1>Editing Powersupply</h1>

<%= render 'form' %>

<%= link_to 'Show', @powersupply %> |
<%= link_to 'See all Power Supplies', powersupplies_path %>

app/views/powersupplies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Powersupplies</h1>

<table class="table table-striped table-bordered table-condensed">
  <thead>
    <tr>
      <th>Select</th>
      <th>Price</th>
      <th>Maker</th>
      <th>Model</th>
      <th>Ps type</th>
      <th>Max power</th>
      <th>Connector</th>
      <th>Rails 12v</th>
      <th>Intel support</th>
      <th>Sli support</th>
      <th>Output ratings</th>
      <th>Dimensions</th>
      <th>Notes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @powersupplies.each do |powersupply| %>
      <tr>
	<td><%= powersupply.select %></td>
        <td><%= powersupply.price %></td>
        <td><%= powersupply.maker %></td>
        <td><%= powersupply.model %></td>
        <td><%= powersupply.ps_type %></td>
        <td><%= powersupply.max_power %></td>
        <td><%= powersupply.connector %></td>
        <td><%= powersupply.rails_12v %></td>
        <td><%= powersupply.intel_support %></td>
        <td><%= powersupply.sli_support %></td>
        <td><%= powersupply.output_ratings %></td>
        <td><%= powersupply.dimensions %></td>
        <td><%= powersupply.notes %></td>
        <td><%= link_to 'Show', powersupply %></td>
        <td><%= link_to 'Edit', edit_powersupply_path(powersupply) %></td>
        <td><%= link_to 'Destroy', powersupply, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Powersupply', new_powersupply_path %>

app/views/powersupplies/new.html.erb
<h1>New Powersupply</h1>

<%= render 'form' %>

<%= link_to 'Back', powersupplies_path %>

app/views/powersupplies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Select:</strong>
  <%= @powersupply.select %>
</p>
<p>
  <strong>Price:</strong>
  <%= @powersupply.price %>
</p>

<p>
  <strong>Maker:</strong>
  <%= @powersupply.maker %>
</p>

<p>
  <strong>Model:</strong>
  <%= @powersupply.model %>
</p>

<p>
  <strong>Ps type:</strong>
  <%= @powersupply.ps_type %>
</p>

<p>
  <strong>Max power:</strong>
  <%= @powersupply.max_power %>
</p>

<p>
  <strong>Connector:</strong>
  <%= @powersupply.connector %>
</p>

<p>
  <strong>Rails 12v:</strong>
  <%= @powersupply.rails_12v %>
</p>

<p>
  <strong>Intel support:</strong>
  <%= @powersupply.intel_support %>
</p>

<p>
  <strong>Sli support:</strong>
  <%= @powersupply.sli_support %>
</p>

<p>
  <strong>Output ratings:</strong>
  <%= @powersupply.output_ratings %>
</p>

<p>
  <strong>Dimensions:</strong>
  <%= @powersupply.dimensions %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @powersupply.notes %>
</p>

<%= link_to 'Edit', edit_powersupply_path(@powersupply) %> |
<%= link_to 'See all Power Supplies', powersupplies_path %>