config/routes.rb
Rails.application.routes.draw do
  root 'base_pages#home'

  get 'base_pages/help'

  resources :towers

  resources :powersupplies

  resources :hdds

  resources :drams

  resources :gpus

  resources :ssds

  resources :cpus

  resources :motherboards

  get 'pc_builds' => 'pc_builds#index'

end

app/models/ssd.rb
class Ssd < ActiveRecord::Base
    scope :selected, -> {where select: "true"}
end

app/controllers/ssds_controller.rb
class SsdsController < ApplicationController
  before_action :set_ssd, only: [:show, :edit, :update, :destroy]

  # GET /ssds
  # GET /ssds.json
  def index
    @ssds = Ssd.all
  end

  # GET /ssds/1
  # GET /ssds/1.json
  def show
  end

  # GET /ssds/new
  def new
    @ssd = Ssd.new
  end

  # GET /ssds/1/edit
  def edit
  end

  # POST /ssds
  # POST /ssds.json
  def create
    @ssd = Ssd.new(ssd_params)

    respond_to do |format|
      if @ssd.save
        format.html { redirect_to @ssd, notice: 'Ssd was successfully created.' }
        format.json { render :show, status: :created, location: @ssd }
      else
        format.html { render :new }
        format.json { render json: @ssd.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ssds/1
  # PATCH/PUT /ssds/1.json
  def update
    respond_to do |format|
      if @ssd.update(ssd_params)
        format.html { redirect_to @ssd, notice: 'Ssd was successfully updated.' }
        format.json { render :show, status: :ok, location: @ssd }
      else
        format.html { render :edit }
        format.json { render json: @ssd.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ssds/1
  # DELETE /ssds/1.json
  def destroy
    @ssd.destroy
    respond_to do |format|
      format.html { redirect_to ssds_url, notice: 'Ssd was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ssd
      @ssd = Ssd.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ssd_params
      params.require(:ssd).permit(:select, :price, :name, :model, :form_factor, :size, :connection)
    end
end

app/helpers/ssds_helper.rb
module SsdsHelper
end

app/views/ssds/_form.html.erb
<%= form_for(@ssd) do |f| %>
  <% if @ssd.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ssd.errors.count, "error") %> prohibited this ssd from being saved:</h2>

      <ul>
      <% @ssd.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :select %><br>
    <%= f.text_field :select%>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :model %><br>
    <%= f.text_field :model %>
  </div>
  <div class="field">
    <%= f.label :form_factor %><br>
    <%= f.text_field :form_factor %>
  </div>
  <div class="field">
    <%= f.label :size %><br>
    <%= f.text_field :size %>
  </div>
  <div class="field">
    <%= f.label :connection %><br>
    <%= f.text_field :connection %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ssds/edit.html.erb
<h1>Editing Ssd</h1>

<%= render 'form' %>

<%= link_to 'Show', @ssd %> |
<%= link_to 'Back', ssds_path %>

app/views/ssds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Ssds</h1>

<table class="table table-striped table-bordered table-condensed">
  <thead>
    <tr>
      <th>Select</th>
      <th>Price</th>
      <th>Name</th>
      <th>Model</th>
      <th>Form factor</th>
      <th>Size</th>
      <th>Connection</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ssds.each do |ssd| %>
      <tr>
	<td><%= ssd.select %></td>
        <td><%= ssd.price %></td>
        <td><%= ssd.name %></td>
        <td><%= ssd.model %></td>
        <td><%= ssd.form_factor %></td>
        <td><%= ssd.size %></td>
        <td><%= ssd.connection %></td>
        <td><%= link_to 'Show', ssd %></td>
        <td><%= link_to 'Edit', edit_ssd_path(ssd) %></td>
        <td><%= link_to 'Destroy', ssd, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ssd', new_ssd_path %>

app/views/ssds/new.html.erb
<h1>New Ssd</h1>

<%= render 'form' %>

<%= link_to 'Back', ssds_path %>

app/views/ssds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Select:</strong>
  <%= @ssd.select %>
</p>

<p>
  <strong>Price:</strong>
  <%= @ssd.price %>
</p>

<p>
  <strong>Name:</strong>
  <%= @ssd.name %>
</p>

<p>
  <strong>Model:</strong>
  <%= @ssd.model %>
</p>

<p>
  <strong>Form factor:</strong>
  <%= @ssd.form_factor %>
</p>

<p>
  <strong>Size:</strong>
  <%= @ssd.size %>
</p>

<p>
  <strong>Connection:</strong>
  <%= @ssd.connection %>
</p>

<%= link_to 'Edit', edit_ssd_path(@ssd) %> |
<%= link_to 'See all SSDs', ssds_path %>